Refactor/unit tests
alexzoul/angular-webpack pull request #50
Opened 2017-07-25 00:57 UTC by alexzoul

2017-07-25 14:45 UTC, cyberdelphos requested changes
Just one ortography comment.

2017-07-25 14:45 UTC, cyberdelphos commented on tests/DOMElement.spec.js
> +  it('should set right attributes with them values to element', () => {
should set **requested**/**correct** attributes with **their** values...

2017-07-25 16:46 UTC, cyberdelphos reviewed
The test for itemsPerSection seems wrong.

2017-07-25 16:46 UTC, cyberdelphos commented on src/scripts/WindowUtils.ts
> +    const withScroll = widthNoScroll - inner.offsetWidth;
scrollBarWidth

2017-07-25 16:46 UTC, cyberdelphos commented on src/scripts/WindowUtils.ts
> +    return withScroll;
scrollBarWidth

2017-07-25 16:46 UTC, cyberdelphos commented on src/scripts/DOMUtils.ts
> +  static itemsPerSection(container: HTMLElement, className: string): number[] {
Maybe **itemsPerRowSection** is a proper name?

2017-07-25 16:46 UTC, cyberdelphos commented on tests/DOMUtils.spec.js
> +    expect(itemsPerSection[0]).to.equals(2);
Why do you expect to be 2 items in section 1 if they surpass the container width (51 + 51 = 102 and 102 > 100)?
It would be itemsPerSection[0] = 1, [1] = 1, [2] =1, [3] = 1.
It looks like something is wrong.

2017-07-26 14:34 UTC, cyberdelphos approved these changes
Missing doc comments in code :(

2017-08-08 18:42 UTC, rodwyn approved these changes

2017-08-08 18:42 UTC, merged